### ISSUE TITLE
Keep npmjs readme in sync with github readme

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu#11]
For the projects I've worked on, I just use the same directory to publish to npm as to publish to github, so no need to worry about keeping the two in sync. (Sometimes the docs will be slightly less up to date, as sometimes docs are updated in github without an npm publish, but this isn't a big deal).

You can have a `.npmignore` file if different from the `.gitignore` file.

+ obviously also true for the other projects (jinqu-odata).

**Comment by umutozel** [comment]
Hmm you are right, I thought having below settings in package.json would update readme, but obviously I'm wrong.

```json
  "files": [
    "dist",
    "readme.md"
  ],
```

Could this be a letter case issue? I renamed it to README.md, will check after next publish.

**Comment by umutozel** [comment]
Yeah, renaming to uppercase worked (made the change on all repos, tried with jinqu-odata).
