### ISSUE TITLE
Bundle Warnings, Add IE 11 support

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu#12]
Getting a large number of warnings when running a web app when using the jinqu package, perhaps due to source map issues, in the Chrome window (pasted below).

If it helps, here's the webpack config that will work with source maps that need double translations (so they go from typescript to javascript, and then javascript to bundled javascript):
https://github.com/solenya-group/solenya-aspnetcore-starter/blob/master/webpack.config.js

So if you reference Solenya package, and hit F12 in chrome, go to the Sources tab, then Page, you can debug Solenya .ts files in the webpack://./node_modules/solenya/src directory

Anyway, here's the warnings:

[HMR] bundle has 12 warnings

./node_modules/jokenizer/dist/lib/ExpressionVisitor.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../../lib/ExpressionVisitor.ts': Error: Can't resolve '../../lib/ExpressionVisitor.ts' in 'C:\Code\feesmonthly\node_modules\jokenizer\dist\lib'./node_modules/jinqu/dist/lib/ajax.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../../lib/ajax.ts': Error: Can't resolve '../../lib/ajax.ts' in 'C:\Code\feesmonthly\node_modules\jinqu\dist\lib'./node_modules/jinqu/dist/lib/array-extensions.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../../lib/array-extensions.ts': Error: Can't resolve '../../lib/array-extensions.ts' in 'C:\Code\feesmonthly\node_modules\jinqu\dist\lib'./node_modules/jinqu/dist/lib/array-query-provider.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../../lib/array-query-provider.ts': Error: Can't resolve '../../lib/array-query-provider.ts' in 'C:\Code\feesmonthly\node_modules\jinqu\dist\lib'./node_modules/jokenizer/dist/lib/evaluator.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../../lib/evaluator.ts': Error: Can't resolve '../../lib/evaluator.ts' in 'C:\Code\feesmonthly\node_modules\jokenizer\dist\lib'./node_modules/jinqu/dist/lib/query-part.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../../lib/query-part.ts': Error: Can't resolve '../../lib/query-part.ts' in 'C:\Code\feesmonthly\node_modules\jinqu\dist\lib'./node_modules/jinqu/dist/lib/queryable.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../../lib/queryable.ts': Error: Can't resolve '../../lib/queryable.ts' in 'C:\Code\feesmonthly\node_modules\jinqu\dist\lib'./node_modules/jokenizer/dist/lib/tokenizer.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../../lib/tokenizer.ts': Error: Can't resolve '../../lib/tokenizer.ts' in 'C:\Code\feesmonthly\node_modules\jokenizer\dist\lib'./node_modules/jokenizer/dist/lib/types.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../../lib/types.ts': Error: Can't resolve '../../lib/types.ts' in 'C:\Code\feesmonthly\node_modules\jokenizer\dist\lib'./node_modules/jinqu/dist/index.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../index.ts': Error: Can't resolve '../index.ts' in 'C:\Code\feesmonthly\node_modules\jinqu\dist'./node_modules/jokenizer/dist/index.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file '../index.ts': Error: Can't resolve '../index.ts' in 'C:\Code\feesmonthly\node_modules\jokenizer\dist'./node_modules/reflect-metadata/Reflect.jsModule Warning (from ./node_modules/source-map-loader/index.js):(Emitted value instead of an instance of Error) Cannot find source file 'Reflect.ts': Error: Can't resolve './Reflect.ts' in 'C:\Code\feesmonthly\node_modules\reflect-metadata'

**Comment by umutozel** [comment]
Hmm, I believe this is due to my tsconfig, I choose to generate .d.ts with source maps, but did not publish .ts files with it. Checking now.

**Comment by umutozel** [comment]
OK, disabled sourceMaps and published packages (jokenizer, jinqu, jinqu-odata, jinqu-fetch, jinqu-axios, linquest).

**Comment by solenya-group** [comment]
Assuming this is a temporary solution?

**Comment by umutozel** [comment]
No no, it was a mistake. I don't want to publish .ts files alongside .js and .d.ts files. I thought about it, debugging npm would be nice, but npm should't contain .ts, it mixes editors/IDEs heads (when with .d.ts, most of them raise warnings about duplicate types).
Config file came from a different project (copy pasta) which is published with .ts, .js and js.map files (no .d.ts).

I tried them and seems OK, but wanted you to try it before closing the issue.

**Comment by solenya-group** [comment]
The great thing about npm is that it's very much geared towards the development experience - which is why they even go so far as to have a `devDependencies` section in the package definition. Being able to debug the original source is sometimes nice, but sometimes a killer feature. This becomes true when 1) the calls to the library are interwoven with application code due to callbacks (which is definitely true for LINQ), and 2) there is a considerable level of abstraction in the source (where ever since Typescript supported async the level of abstraction experienced a huge bump up).

So regarding the actual mechanics of making it work, the issue with duplicate type warnings seems like a trivial config issue, no? Also the `.ts` files shouldn't be *alongside* the `.js` files; in Solenya the `.js`, `.d.ts`, and `.js.map` files are in the `dist` directory, and the source files are in the `src` directory; no issues with duplicate type warnings.

So mostly seems like a significant win with very little cost, but as always I'm curious if there's other downsides I've missed.

**Comment by solenya-group** [comment]
Also not sure if related, but jinqu is now choking the stackblitz autocomplete:
https://stackblitz.com/edit/jinqu-oftype

**Comment by umutozel** [comment]
I'm using `lib`folder (instead of `src`), so same with solenya. I'll try an npm with local sinopia, using VS Code and VS.
Sometimes I might be too cautious, probably I had duplicate errors when I used global declarations (pre-modules).

**Comment by umutozel** [comment]
published all packages with .ts and .js.map files.

This process is like a lesson on the importance of integration tests and how unit tests are not always sufficient :)

**Comment by solenya-group** [comment]
Getting this error with jinqu 0.59:

ERROR in [at-loader] ./node_modules/jinqu/dist/lib/types.d.ts:1:28 
    TS2307: Cannot find module 'jokenizer'.
ERROR in [at-loader] ./node_modules/jinqu/dist/lib/query-part.d.ts:1:28 
    TS2307: Cannot find module 'jokenizer'.

Also, previously importing `jinqu` anywhere in the project would make the array prototypes visible; now to compile it needs to be imported per project. Perhaps this is OK (in C# you have to import System.Linq). I'll update the docs to match the behaviour when we confirm what's best.

**Comment by umutozel** [comment]
Do you have this project on github? I tried it with a mini sample by adding all packages and seemed OK. I'd love to fork and try on same environment. I'm open to Live Share too.

**Comment by solenya-group** [comment]
Seems to have just been a npm glitch; did the usual clean/close/reopen Visual Studio and it's working.

**Comment by umutozel** [comment]
It's a relief, I panicked a little, what could be wrong (translates into what did I miss) this time :)

**Comment by solenya-group** [comment]
Well at this stage of the project no need to panic; a good time to be able to make mistakes & have rapid iteration.

Anyway, there may be an IE (11) issue. A syntax error occurs on this line:

```javascript
 Query.prototype[Symbol.iterator] = function () {
        return this.provider.execute(this.parts);
    };
```

**Comment by umutozel** [comment]
Yeah you are right, I wasn't that serious (but a little serious)

IE11 doesn't support `Iterator`s, or even `Symbol`s. We need a polyfill [like this](https://www.npmjs.com/package/es6-symbol).

**Comment by solenya-group** [comment]
I'm a bit murky on this topic, but Typescript seems to compile iterators to es5:

https://typescript-play.js.org/?target=1#code/GYVwdgxgLglg9mAVAAgIYCd2oJ4EkoCmWUc6AFBugFxpjYDaAugJTIDeAUMssKcmQDcMyGMgC8yAAwBuEcgA8aTADoANgTABzKAAtZMANQHWnbt2wwCqgCZL09GI2ldkAXw7uO6qHZwAWcWR6AEZJABpkACZw5ABmSScOIXQRKACJShx8IlQSckzsP2ZnCAQAZzh1NThNMhg05TACAA8oMmZi5AB6LvZkIVUQAhpgiOsEYZ5UVTKCNw5SsAqq1Rq6hqbW9s6evoGhmkixiZpgadn5xeWCatr6v0aWto7ZXbZ+6YO446bT87n3FdKjdVncNk9tq9eu99pNwNYCMAYE1rD9JlB0EM3EA

Note IE 11 support is a must have feature (while there's only a small % of IE users, there's a large % of website owners who require that this small group is supported).

**Comment by umutozel** [comment]
I agree, we should definitely support IE 11, I thought polyfills would be enough. That's why I targeted `es5` and add `es2015` to libs (I didn't want to add polyfills myself, left it to consumers of the package).

Now I'm playing with the tsconfig, and will try to test on a win machine (I'm using a mac daily).

**Comment by umutozel** [comment]
Finally with IE support. 
I discovered a weird behavior with TypeScript. It tries to compile my "types.ts" file from node_modules folder. Fixed it with renaming to "shared.ts", it took me forever to find out this.

**Comment by solenya-group** [comment]
Awesome, thanks.

**Comment by solenya-group** [comment]
As of 0.61, IE is broken. A bit of nasty one here, as the failure is silent - i.e. no errors are returned in the F12 console/debug window.

**Comment by umutozel** [comment]
I believe being able run tests on a browser would be awesome and will check almost every line and code branch of the project.
But I've been looking at options, it will not be that easy. It seems I'll need webpack, and I always needed a few days just to configure webpack. I'm starting to work on it now, and when I find a working template/solution, will apply to all jinqu projects. Will post here.

**Comment by solenya-group** [comment]
> I always needed a few days just to configure webpack.
;)

Just thinking out loud... it seems running tests on the browser would be a robust solution. That's pretty involved though. Are there any npm packages that integrate with the build process/webpack that can test for IE11 compatibility in terms of language usage / function calls? Did a quick search found this:

https://github.com/jgardella/compat

It's a couple years old - but maybe it's worth running to see if it would have picked up the last issue. Also, maybe there's a better package out there that does the same thing (so hard sometimes to discover npm packages).

**Comment by solenya-group** [comment]
More static analysis tools...

https://github.com/webhintio/hint  
https://github.com/MicrosoftEdge/static-code-scan (though this is now deprecated and recommends to use the former tool)

**Comment by umutozel** [comment]
Compat said "Compatibility table already up to date." every way I tried, maybe I couldn't configured it correctly.
Hint wants a website to check, so I combined it with my other goal (running tests on browser). Here's what I did;

* Dynamically compile test files (combining with mocha files) with webpack
* Create a Html mocha template
* Host output using webpack dev server (in-memory)
* Get results using mocha-headless-chrome (of course with nyan cat reporter :))

Everything worked great, just when I was looking for a IE launcher and telling myself this could be a great tool if it could be configurable, my duplication senses started to tingle. I couldn't put my finger on it, but I'm sure I used a tool like that, then it hit me: **karma**.

So, I configured karma to run my tests on headless chrome, headless firefox and IE (for windows only). I did this for jokenizer project only for now, will be implementing for other projects soon.

**Comment by umutozel** [comment]
Jinqu karma tests are working, published 6.0.2 npm.
I couldn't figure out the problem with karma, I needed to use my custom script.
I will definitely publish that as a repo, maybe it can be published as a package or something.

**Comment by umutozel** [comment]
**Jokenizer**, **jinqu** and **jinqu-odata** now runs **karma** tests.

But I couldn't figure a way out to make **karma** work for **linquest**. **Punycode** (**karma-typescript** dependency) is ES6 only. So, I removed all **karma** and added my dumb script to check manually on browsers.
`npm run browser`
will build the output, start a dev-server and run tests via headless chrome. But doesn't stop the dev-server, then I check using Internet Explorer and stop the script with **Ctrl+C** :)

Could you check with latest packages?

**Comment by solenya-group** [comment]
Confirming jinqu 0.62 working with IE. FWIW in one project I've got we didn't need IE support so was able to happily just continue using jinqu, while in another we did need IE support so to meet a deadline I had to rip out jinqu out and replace it with some array prototype extensions. One thing that did occur to me after doing this was that it was nice & tidy to not have to go `toArray`, and I wasn't leveraging performance benefits of lazy evaluation anyway. Just a thought.

**Comment by umutozel** [comment]
Great news.

I always felt the same, `toArray` shouldn't be necessary. We can iterate over a query directly, but I don't know, it could be great if we have a C# like usability.

I had done a weird trick back in the time for another similar project. I realized 3rd party libraries usually satisfy with duck typing and `length` is almost always called first. So, I added a `length` property to query type, in the getter, I executed the query and set indexes with result. Code would be similar to this:

```JavaScript
Query.prototype.length = Object.defineProperty(Query.prototype, "length", {
    get: function () {
        var result = this.toArray();
        if (!(result instanceof Array)) {
            result = [result];
        }

        var i = result.length;
        while (this[i] !== undefined) {
            delete this[i++];
        }

        for (i = 0; i < result.length; i++) {
            this[i] = result[i];
        }

        return result.length;
    },
    enumerable: true
});
```

I know it's weird and it doesn't feel right but this way we can use queries like arrays. Just need a way to trick TypeScript.

Afterthought, this is not LINQ way. Leaving for now, until we find a better way.
