### ISSUE TITLE
toArray return type

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu#14]
A very common pattern is to have a function ending with `toArray`. My expectation was that the type signature would be `T[]`, but the type signature is an intersection type between `T[]` and `InlineCountInfo`. So have to add boilerplate to explicitly modify the return type, otherwise the signature is polluted. This seems to break the 90/10 principle, as the vast majority of the time you don't care about getting the inline count.

**Comment by umutozel** [comment]
Yeah, that bothers me too, but I couldn't find a way to add a type dynamically for queries requiring inline count. So I always return with `InlineCountInfo`, if `inlineCount` is not called, `$inlineCount` will be undefined. And adding a new generic parameter seemed overkill.
Do you have any suggestion?

**Comment by solenya-group** [comment]
Well my naive expectation would be that the last line of the query would be `toCountedArray` if someone wanted to get the inline count...?

**Comment by umutozel** [comment]
OK I admit, that was easier than expected. I changed the whole design to remember an extra result interface with a new generic parameter. No more pollution. Obviously I'd chosen my convenience over 90/10.

**Comment by umutozel** [comment]
```typescript
type IQuery<T, TExtra = {}> {
    inlineCount(value?: boolean): IQuery<T, TExtra & InlineCountInfo>;
    where(predicate: Predicate<T>, ...scopes): IQuery<T, TExtra>;
}
```
This works as expected. I will do the same for jinqu-odata.

I saw your message after completing the above design, that would work too. 
But I wanted to have `inlineCount` as a query part, I did some conditional query building previously, sometimes we need to enable `inlineCount`, call some methods on query (like `skip`, `take`), and return the query without executing it.

**Comment by umutozel** [comment]
One more thing, this way we will be able to add extra results to queries easily. 
I had hard time when I first try remote query execution with Ajax Request information.
Now we can have a method like;

```typescript
includeResponse(): IQuery<T, TExtra & IResponseInfo>
```
IResponseInfo can contain response headers etc..

**Comment by umutozel** [comment]
Just wanted to start a discussion on remote providers and their extra informations. I did a lot of thinking while coding jin-qu projects, how can I add support to make it easy to get extra information (like Http Response info etc..).

I didn't want to return a wrapper object, like this:

```typescript
interface Result<T> {
  value: T;
}
// ...

interface Query<T> {
    toArray(): Result<T[]>
}

// usage
const result = query.first().value;
```

Obviously, with this approach I can add any extra information to results, but it's not, hmm how to say it, stylish.

Now, new TExtra will add this support (just pushed the code, maybe you want to check it out), but for only reference type results, we still won't have a way to access extra information for primitive types. For exampe:

```typescript
// first can return extra information
first(predicate?: Predicate<T>, ...scopes): T & TExtra;

// also won't work when result is null
firstOrDefault(predicate?: Predicate<T>, ...scopes): T & TExtra;

// but any can't, we can't attach properties to primitive types
// if we box them (e.g. new Boolean(value).extra = extra), 
// the value won't be truthy and user must use the value accordingly (value === true, or if(value) won't work)
any(predicate?: Predicate<T>, ...scopes): boolean;

```

I hope it's clear, I just wanted to get your opinion on this.

**Comment by solenya-group** [comment]
I might be looking at this simplistically, but my default expectation would be that the type of the following function would be `User`:

```typescript
function getCurrentUser() {
  return this.users.first(u => u.id == currentUserId)
}
```
I'd be happy to call a separate method if I care about `T & TExtra`. So as with arrays, by default, I want unpolluted types (at both compile time and runtime), but if I opt in, then my types can have extra information (at both compile time and runtime).

More thinking out loud, but you've got monads like Array of T, Task of T, Nullable of T. Maybe you want an Extra of T?

**Comment by umutozel** [comment]
```typescript
function getCurrentUser() {
  return this.users.first(u => u.id == currentUserId)
}
```
This shouldn't pollute the code, here are a few screenshots from tests:

First w/o `InlineCountInfo`
<img width="842" alt="firstwithoutinlinecount" src="https://user-images.githubusercontent.com/3070050/52068264-64024e80-258d-11e9-862c-80eb214bc95f.png">

First after `inlineCount` called
<img width="962" alt="firstwithinlinecount" src="https://user-images.githubusercontent.com/3070050/52068271-682e6c00-258d-11e9-80c4-997cb1febe42.png">

TypeScript is smart enough to ignore T & EmptyType.

I didn't want to add too many executing methods, `first, firstAsync, firstWithExtra, firstWithExtraAsync, any, anyAsync, anyWithExtra, anyWithExtraAsync` etc..

But main problem with my design is with primitive returning functions, we cannot add properties to primitive types. If I change `T` to `Extra<T>` after a call to `inlineCount`, `toArray` will return `Extra<T>[]`. 
Hmm unless I write a dynamic type unwrapper. You gave me a neat idea :)

**Comment by umutozel** [comment]
With Extra<T>, I need to unwrap it to T for every lambda, otherwise `where(predicate: Predicate<T>)` would become `where(predicate: Predicate<Extra<T>>)`.

I want to add support for extra information and dynamically return wrapped result for executing functions, but, my overengineering sense is tingling.

I thought this would work

```typescript

type Empty = {};
type Result<T, TExtra> = { value: T } & TExtra;

interface IMyQuery<T, TExtra = Empty> {
    inlineCount(): IMyQuery<T, TExtra & InlineCountInfo>
    any(): Empty extends TExtra ? boolean : Result<boolean, TExtra>;
    first(): Empty extends TExtra ? T : Result<T, TExtra>;
    where(): IMyQuery<T, TExtra>;
    toArray(): T[] & TExtra;
}

class Company {
    id: number;
    name: string;
}

const q = <IMyQuery<Company>>{};

const any1 = q.any();       // boolean
const any2 = q.inlineCount().any();     // expected Result<boolean, TExtra> but got boolean
const first1 = q.first();       // Company
const first2 = q.inlineCount().first();     // expected Result<Company, TExtra> but got Company
```

**Comment by umutozel** [comment]
I found the problem, If an interface doesn't have any non-optional member, TypeScript considers it as an empty type. When I removed the `?` from `$inlineCount`, it worked.

```typescript
type Result<T, TExtra> = {} extends TExtra ? T : { value: T } & TExtra;

interface IMyQuery<T, TExtra = {}> {
    inlineCount(): IMyQuery<T, TExtra & InlineCountInfo>;
    any(): Result<boolean, TExtra>;
    toArray(): T[] & TExtra;
}

interface Company {
    id: number;
    name: string;
}

const q = <IMyQuery<Company>>{};

const any1 = q.any();    // boolean
const any2 = q.inlineCount().any();    // Result<boolean, InlineCountInfo>
```

This also avoids pollution.

**Comment by umutozel** [comment]
I implemented with TExtra approach. Unless we want any extra info, results will be only T, otherwise will be wrapped into:
```typescript
{ value: T } & TExtra
```
