### ISSUE TITLE
String interpolation?

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu#4]
Not sure if I have a mental block here, but I'm wondering why this is necessary:

```typescript
const filtered = orders.where('c => c.id > value', { value: 3 })
```
As opposed to simply using string interpolation:

```typescript
const value = 3
const filtered = orders.where(`c => c.id > ${value}`)
```

**Comment by solenya-group** [comment]
Is the advantage that the callee handles the escaping, rather than the caller? If so, what escaping mechanism is used?

**Comment by umutozel** [comment]
You are absolutely right, we could use interpolation, but my goal was to create same tests in `query-part.string.spec` as in `query-part.spec` to be sure all methods works with string lambdas (and other parameters are the same). You can see they are copy-pasted :)

For the escaping, I used [MDN String Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String) in `jokenizer` project. We can use same escape characters as JavaScript in our strings.

**Comment by umutozel** [comment]
I'm closing this for now.
