### ISSUE TITLE
asQueryable

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu#7]
Apologies for logging an issue for what might just be a documentation question, but what's the purpose of `asQueryable` (and `q`)?

In other words, what's the difference between these two lines:

``` typescript
[1,2,3].where (x => x % 2 == 0)
[1,2,3].asQueryable().where (x => x % 2 == 0)
```

**Comment by umutozel** [comment]
No problem.

Yeah you're right, it's a documentation issue, there isn't any difference, 

`asQueryable` is just there if someone doesn't want to or can't use Array proto extensions. To be honest, I inspired from C# Linq.
`q` is just a shortcut, I hated writing `asQueryable` while coding tests.

**Comment by solenya-group** [comment]
Are you saying it's possible someone would want to yet couldn't use the Array proto extensions? How?

**Comment by umutozel** [comment]
Maybe mixing with another library could overwrite our implementation.
Or a better case, there are 3 functions in IQuery overlapping with Array (concat, join and reverse).
To use these directly, we have to create a query from our Array.

```typescript
[1, 2, 3].join()    // Array's join method
[1, 2, 3].asQueryable().join()
// or just being lazy
[1, 2, 3].q().join()
```

Maybe there are other scenarios I couldn't think of, but I was thinking about above cases when adding `asQueryable`.

**Comment by solenya-group** [comment]
Created a PR explaining this in the docs.

https://github.com/jin-qu/jinqu/pull/8

**Comment by umutozel** [comment]
I'm closing this for now. Thanks for the PR.
